#!/bin/sh
height=$(xrandr | grep ' connected' | awk '{print $4}' | sed -e 's/^\(.*\)x\(.*\)+\(.*\)+\(.*\)/\2/g')

if [[ $height == "1080" ]]; then
	cp -f $(dirname $0)/config-1080 $(dirname $0)/clearine.conf
else
	cp -f $(dirname $0)/config-768 $(dirname $0)/clearine.conf
fi
